---
# - name: firewall 停止確認
  # shell: firewall-cmd --list-all
  # register: result
  # ignore_errors: true
  # changed_when: false
  # always_run: yes
  # tags: CentOs7

- name: stoped  firewall
  command: systemctl stop firewalld.service
  # when: result|success and result.stdout.find('FirewallD is not running') == -1
  tags: CentOs7

- name: disabled firewall
  command: systemctl disable firewalld.service
  # when: result|success and result.stdout.find('FirewallD is not running') != -1
  tags: CentOs7

- name: iptables 停止確認
  shell: chkconfig --list iptables
  register: result
  ignore_errors: true
  changed_when: false
  always_run: yes
  tags: CentOs6

- name: stop ip tables
  service: name=iptables state=stopped enabled=false
  when: result|success and result.stdout.find('on') != -1
  tags: CentOs6

