---
- name: timezone確認
  shell: awk -F\" '{ print $2}' /etc/sysconfig/clock
  register: result
  ignore_errors: true
  changed_when: false
  always_run: yes
  tags:
    - CentOs7
    - CentOs6

- name: change local time
  copy: src=/usr/share/zoneinfo/Japan dest=/etc/localtime owner=vagrant force=yes
  when: result.stdout != "JST"
  tags:
    - CentOs7
    - CentOs6
