---
- name: install apache
  yum: name=httpd state=latest
  tags: apache

- name: install apache modules
  yum: state=installed name={{ item }}
  with_items:
    - mod_ssl
    - openssh
  tags: apache

- name: write the apache config file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  tags: apache

- name: create virtual host file for vhosts
  template: src=vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf
  tags: apache

- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes
