---
- name: install apache
  yum: name=httpd state=latest
  tags:
    - apache24
    - apache22

- name: install apache modules
  yum: name={{ item }} state=latest
  with_items: install_apache_modules
  tags:
    - apache24
    - apache22

- name: write the apache config file
  template: src=httpd24.conf.j2 dest=/etc/httpd/conf/httpd.conf
  tags: apache24

- name: write the apache config file
  template: src=httpd22.conf.j2 dest=/etc/httpd/conf/httpd.conf
  tags: apache22

- name: create virtual host file for vhosts
  template: src=vhosts24.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf
  tags: apache24

- name: create virtual host file for vhosts
  template: src=vhosts22.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf
  tags: apache22

- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes
  tags: apache24

- name: be sure httpd is running and enabled
  service: name=httpd state=started enabled=yes
  tags: apache22
