---
- name: installed ruby
  yum: name=ruby state=present
  tags: ruby

- name: installed ruby modules
  yum: name={{ item }} state=present
  with_items:
    - ruby-devel
    - rubygems
  tags: ruby

- name: installed gem
  gem: name={{ item }} state=present user_install=no
  with_items:
    - rake
    - rb-inotify
  tags: ruby
