---
- name: stoped firewall
  command: systemctl stop firewalld.service
  tags: CentOs7

- name: disabled firewall
  command: systemctl disable firewalld.service
  tags: CentOs7

- name: stop ip tables
  shell: service iptables stop
  tags: CentOs6
