---
- name: installed mysql
  yum: name=mysql-community-server enablerepo=mysql56-community state=present
  tags: mysql

- name: install MySQL-python
  yum: name=MySQL-python state=latest
  notify: setup mysql
  tags: mysql

- name: put my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf
  tags: mysql
