---
- name: installed libmcrypt
  yum: name={{ item }} enablerepo=epel state=present
  with_items:
    - libmcrypt
    - libmcrypt-devel
  tags: php56

- name: installed gd, ImageMagick
  yum: name={{ item }} enablerepo=remi state=present
  with_items:
    - gd-last
    - ImageMagick-last
  tags: php56

# phpとモジュール郡をinstall
- name: installed php
  yum: name=php enablerepo=remi-php56 state=present
  tags: php56

- name: installed php module
  yum: name={{ item }} enablerepo=remi-php56 state=present
  with_items: php_packages
  tags: php56

- name: put php.ini
  copy: src=php.ini dest=/etc/php.ini
  tags: php56

- include: memcache.yml
- include: composer.yml
