---
- name: stat /etc/httpd/conf.d/php.conf
  stat: path=/etc/httpd/conf.d/php.conf
  register: phpconf_stat
  when: env == "local"
  changed_when: false
  ignore_errors: true
  tags: php56

- name: set PHP_IDE_CONFIG env to /etc/httpd/conf.d/php.conf
  lineinfile: dest=/etc/profile line="export PHP_IDE_CONFIG='serverName=vagrant'"
  when: phpconf_stat.stat.exists
  tags: php56

# 自動生成されるlogファイルは所有者がrootなので先にvagrant userでファイルを生成しておく
- name: make logfile
  file: path={{ xdebug_logfile_path }} state=touch owner=vagrant
  tags: php56


